import HeaderBar from "./_components/HeaderBar";
import Navigation from "./_components/Navigation";
import "./globals.css";
import { CssBaseline, Stack } from "@mui/material";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather Forecast Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CssBaseline />
        <Stack direction="column">
          <HeaderBar />
          <Stack direction="row">
            <Navigation sx={{ flexShrink: 0 }} />
            <Stack
              direction="column"
              component="main"
              sx={{ flexGrow: 1, p: 3 }}
            >
              {children}
            </Stack>
          </Stack>
        </Stack>
      </body>
    </html>
  );
}
